### ISSUE TITLE
Checkpoint exporter doesn't generate the required files.

### ISSUE THREAD

**Issue by AndreaLombax** [teelinsan/camoscio#2]
Hello,
I was trying to finetune Camoscio on my dataset for a particular task. Following the steps listed in the README file, the actual finetuning step that is started by the file finetune.py doesn't work, because it can't find the  tokenizer files in the directory:

> OSError: Can't load tokenizer for 'camoscio_merged_ckpt'. If you were trying to load it from '[https://huggingface.co/models'](https://huggingface.co/models%27), make sure you don't have a local directory with the same name. Otherwise, make sure 'camoscio_merged_ckpt' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

The save_pretrained method used in scripts/checkpoint_exporter.py doesn't generate a classic huggingface model directory. Usually, in the HF model directory some tokenizer files should be read, such as tokenizer.model, tokenizer_config.json and so on. How should I solve this issue?

**Comment by teelinsan** [comment]
Hi @AndreaLombax,
looking at this issue. I'll update you soon

**Comment by teelinsan** [comment]
Now it should work. Follow the new instruction in the readme for fine-tuning.
