### ISSUE TITLE
Keyword argument 'enable_lora' problem

### ISSUE THREAD

**Issue by AlessandroAstorino2** [teelinsan/camoscio#3]
I was trying to run the Demo Colab Notebook but it failed with the following error:

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'enable_lora'

generated from the line:

model = PeftModel.from_pretrained(model, "teelinsan/camoscio-7b-llama")

Can you please help me solve it?

**Comment by teelinsan** [comment]
Hi,
thank you for pointing this out.
I should have fixed the issue, can you try now?
